### PR TITLE
README: fix typo

### PR DESCRIPTION
**Pull request by angristan**

### CODE REVIEW

**Comment by brauner** [comment]
Thank you for the patch. Could you please add a signed-off-by line to your commit? That should be as easy as `git commit -s`:
```
Signed-off-by: First Second <valid@email.com>
```

**Comment by angristan** [comment]
Should be good now 👍

**Comment by brauner** [comment]
Sweet, thanks!

**Comment by angristan** [comment]
You're very welcome 😄

**Pull request merged**
